#!/bin/bash

subdomain_info() {
  local domain="$1"
  local subdomain="$2"
  
  if [[ -z "$sdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$sdomain")
  fi
  
  for sub in "${subdomains[@]}"; do
	  line=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	  echo "$sub $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
  done
}

subdomain_info "$1" "$2"
