#!/bin/bash

subdomain_info() {
  local domain="$1"
  local subdomain="$2"
  
  if [[ -z "$sdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$sdomain")
  fi
  
  for sub in "${subdomains[@]}"; do
    destination=$(dig +short "$sub.$domain" | awk '{print $1}')
    record_type=$(dig +short "$sub.$domain" | awk '{print $4}')
    
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

subdomain_info "$1" "$2"
