#!/usr/bin/env bash

# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER /var/www
sudo chown -R $USER /etc/nginx/sites-available/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo service nginx start
sudo sed -i '24i\rewrite ^/redirect_me https://twitter.com/ai_optimizer permanent;' /etc/nginx/sites-available/default
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo sed -i '49i\\tadd_header X-Served-By \$hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
