#!/usr/bin/env bash
#display numbers from 1 to 20
i=1
while [ "$i" -le 20 ]
do
	if (( i==4 ))
	then
	echo $i
	echo "bad luch from China"
	elif (( i==9 ))
	then
	echo $i
	echo "bad luck from Japan"
	elif (( i==17 ))
	then
	echo $i
	echo "bad luck from Italy"
	else
	echo $i
	fi
	((i++))
done
